### ISSUE TITLE
Doorstop does not work on Valheim

### ISSUE THREAD

**Issue by BlueAmulet** [NeighTools/UnityDoorstop#10] opened 2021-02-10 18:07 UTC
Valheim is a 64bit Unity 2019.4.16 game.
With Doorstop_x64_3.0.2.2, the game just crashes immediately
With Doorstop_x64_3.1.0.0, the game starts, but the targetAssembly appears to not be running at all
I have tested with BepInEx (with the newer 3.1.0.0 dll) and the example Doorstop.dll (moved to the game folder per the path in doorstop_config.ini), doorstop_is_alive.txt did not appear
I have tested Doorstop as winhttp.dll and version.dll, neither worked
Doorstop itself appears to work, setting redirectOutputLog=true does result in an output_log.txt, just not the targetAssembly

**Comment by ghorsington** [comment] 2021-02-10 18:34
Greetings!

Doorstop and BepInEx are known to work with Valheim. The problem is that current builds of the game come with stripped mono base class library assemblies. In other words, some unused code was removed from game assemblies. In case of Valheim, many types used by BepInEx (and even example assembly in this repo) are stripped away which. Doorstop itself does its job fine.

At the moment, the fix is to restore the stripped assemblies by taking them directly from Unity Editor 2019.4.16.  
I already did that as an example for Valheim:

[unstripped_managed.7z](https://cdn.discordapp.com/attachments/624272422295568435/807143857375412264/unstripped_managed.7z)

Simply extract this archive into `Valheim_Data\Managed` folder and overwrite when asked. After that BepInEx will indeed boot:

![image](https://user-images.githubusercontent.com/13762037/107552618-68ca5600-6bdc-11eb-9750-ebbdf42fed41.png)

***

**In general**, I would suggest to contact the game developer and ask them to disable assembly stripping when building. Assembly stripping is not enabled by default in Unity which means that a developer for Valheim explicitly enabled it.  

If you are a Unity game developer (or contact a developer for a Unity game): There are many reasons why assembly unstripping is not a good option for Unity games. Here is a list of them:

* **It does not actually save enough space to matter** -- for example, Valheim's `Managed` folder is 6.71 MB by default and 16.1 MB when using default unstripped DLLs. If just a 10 MB difference still sounds like a lot, the difference is just about 1% of the entire game size (about 1 GB). If you want to optimize your game size, optimize your assets first.
* **Steam downloads games compressed (and games are often downloaded in archives). Managed IL assemblies are often surprisingly compressible** -- with LZMA, the size of the unstripped `Managed` folder becomes about 4.3 MB. The size of the compressed and stripped `Managed` folder of Valheim is in turn 2.0 MB using LZMA. In other words, instead of downloading 10 MB you're downloading about 2 MB more. At the same time, most other assets like images and audio are much less compressible. As such, if you want to really save size, optimize your assets and not assemblies.
* **In the end you're not preventing modding** -- unstripping assemblies is a fairly easy process of grabbing them from Unity Editor. At most, you're just creating a nuisance for modders. And before you think about turning to using Il2Cpp thinking it will stop modding: BepInEx supports modding Il2Cpp games fine.

All in all, if you're a developer, please do not enable assembly unstripping in Unity. If you are unsure how, it is extremely easy to do in Player settings:

![image](https://user-images.githubusercontent.com/13762037/107554863-2bb39300-6bdf-11eb-848b-a154a48c8436.png)

***

I will close this issue as it is confirmed not to be Doorstop one. I'll however also pin this one for other Valheim modders to see until the developer stop shipping their assemblies stripped.

**Closed by ghorsington** 2021-02-10 18:34 UTC

**Comment by opl-** [comment] 2021-02-12 00:01
It seems that the `unstripped_managed.7z` file you sent is missing some dlls from it that prevent using MonoMod with the game. In my case, as a Linux user, the missing dlls were `System.Security.dll`, `System.Numerics.dll`, and `Mono.Posix.dll`. Someone else running on Windows apparently has copied all files from Unity and didn't find `System.Security.dll` nor `Mono.Posix.dll` in there, so it's possible Windows uses slightly different dlls.

As I already have mono installed, I was able to find the aforementioned files under `/usr/lib/mono/4.5/`. I'm including them below for the convenience of anyone reading, but feel free to get them yourself from a source more trustworthy than a random stranger online. [missing-unstripped-linux.zip](https://github.com/NeighTools/UnityDoorstop/files/5969034/missing-unstripped-linux.zip)

**Comment by BlueAmulet** [comment] 2021-02-12 18:14
In the Windows Unity installation they're in `2019.4.16f1\Editor\Data\MonoBleedingEdge\lib\mono\4.5`

**Comment by ghorsington** [comment] 2021-02-12 18:21
> It seems that the unstripped_managed.7z file you sent is missing some dlls from it that prevent using MonoMod with the game.

Thanks for the info. I updated the archive in the original message to include those missing DLLs.

**Comment by AmyNicole8715** [comment] 2025-04-10 13:10
@ghorsington 
> At the moment, the fix is to restore the stripped assemblies by taking them directly from Unity Editor 2019.4.16. I already did that as an example for Valheim:
> 
> [unstripped_managed.7z](https://cdn.discordapp.com/attachments/624272422295568435/841990037935882250/unstripped_corlib.7z)
> 

The archive has timed out or otherwise been deleted. Would you be willing to tell me what the specific files are? So I may patch mine and add a todo for myself to work on a patch for those of us needing to use r2Modman on Ubuntu

Idk if this is related but my start modded option whines about a lack of a 32 bit driver and i do not understand why as i thought even was 64 now?

**Comment by opl-** [comment] 2025-04-10 15:19
You can send a Discord CDN link in any Discord channel, which generates a new token and allows downloading the file using the new link. I don't have a convenient place to reupload the file, so here's a listing of its contents instead:

<details>
<summary>Contents of <code>unstripped_managed.7z</code></summary>

```
sha1                                        size modified    name
c04e331b6415bf566e1aa26550bf794651704c7c  212480 2021-02-04  Mono.Posix.dll
36890188d80598132d63561ded707e641282f2a1  309248 2021-02-04  Mono.Security.dll
043003bb40aa33670af615dca95e5efe222e2fe8 4065792 2021-02-04  mscorlib.dll
19c48c22f489db0d3d9e5bba1768a09eb485af07  122368 2021-02-04  System.Configuration.dll
edce976a9dd559897a3e7ff62ddf6990e4b90e5a 1017856 2021-02-04  System.Core.dll
c06608c97997383f007ea5671c7a422d003e9522 2724352 2021-02-04  System.dll
b80a3491016d8abc2d617d73f96799ca47e0a2f9  114688 2021-02-04  System.Numerics.dll
89501687cd4098b18b634e7e6923e76eea9efa52  183296 2021-02-04  System.Security.dll
5aee1f7cad049da727577d2f4f55cfc422de8455 3151872 2021-02-04  System.Xml.dll
6704b9ed3b8bc8936495d520299d6fc41b9c4c2e   12288 2021-03-31  UnityEngine.AccessibilityModule.dll
5a0f7431d42d1890a521d15d1903c9d558ac5f71   44544 2021-03-31  UnityEngine.AIModule.dll
604c13da5fd8a13cfa16ea671e2652fa04af3b7c   57344 2021-03-31  UnityEngine.AndroidJNIModule.dll
f15a21e03c3fede6a3d43f21158159c0867b0f1c  145920 2021-03-31  UnityEngine.AnimationModule.dll
accfed6301a87711cb6d6610ee2161fadfc35253   12800 2021-03-31  UnityEngine.ARModule.dll
a52a6a40189b1af823283b3a8ebb358f491705c4   21504 2021-03-31  UnityEngine.AssetBundleModule.dll
6868cd8f91f488809c35aab83c9a76abd125d76f   57856 2021-03-31  UnityEngine.AudioModule.dll
bc718b2365513ac4e0e59f1beb354d3b32688a56   15360 2021-03-31  UnityEngine.ClothModule.dll
b77b62f5d06cf05ab75d541e7335309e0b0f7e65   10240 2021-03-31  UnityEngine.ClusterInputModule.dll
eb9527d9dde55fa1114b2cc81d22de1da978d91b    9216 2021-03-31  UnityEngine.ClusterRendererModule.dll
da05e380322ca5a312f4c168bfe4887b9e6fc6d4 1007616 2021-03-31  UnityEngine.CoreModule.dll
4016319e737ab17577bd8f2d7ffe0ab1660ede1c    9728 2021-03-31  UnityEngine.CrashReportingModule.dll
3f8bd6df7f06e54ebb679d8e3f892d9027559c83   13312 2021-03-31  UnityEngine.DirectorModule.dll
66a909e14c39da910ab885716de1d205add8e84f   84992 2021-03-31  UnityEngine.dll
97f97fc585dbcb63fec24f878d7eb2b9ab86a399   17920 2021-03-31  UnityEngine.DSPGraphModule.dll
4f8a5e137040da21367423a936294b9460aaa565   27136 2021-03-31  UnityEngine.GameCenterModule.dll
f105637a3e300f3869432046b27339bdc24d3c73   13824 2021-03-31  UnityEngine.GridModule.dll
648ff9d56bcae49fae899f646c06d2f9c86f9192    8704 2021-03-31  UnityEngine.HotReloadModule.dll
83655db29cf195c34896213d0f366c9e073db055   13312 2021-03-31  UnityEngine.ImageConversionModule.dll
e93b74bf2de54a2db924760c4250d4037152a144  156160 2021-03-31  UnityEngine.IMGUIModule.dll
fd9ab9232081186f880b165af36cd29612a2ab8d   25600 2021-03-31  UnityEngine.InputLegacyModule.dll
270b7c60ea30ea700c7d4050f4bf5a4dc75aa2bb   12288 2021-03-31  UnityEngine.InputModule.dll
e618615c9916601182c54d761ab3b0126c973b40   10752 2021-03-31  UnityEngine.JSONSerializeModule.dll
e922395610753a0ba3b22c566dc7a47d16c751d6    9728 2021-03-31  UnityEngine.LocalizationModule.dll
3d4b819bebe665f4d8916aa52a4093b91a17a9ec  135168 2021-03-31  UnityEngine.ParticleSystemModule.dll
6ca82754d2077a874f3225def34255bb692025c0    9216 2021-03-31  UnityEngine.PerformanceReportingModule.dll
4c365d8ffce72c2beea0b69454656405f8a52728  105984 2021-03-31  UnityEngine.Physics2DModule.dll
cb5717fb6dceefb3689ee294a87d1538e96cbe25   87040 2021-03-31  UnityEngine.PhysicsModule.dll
09d6a7d2f492a963d0aaf1ea59fc46ecd6b205a6    8704 2021-03-31  UnityEngine.ProfilerModule.dll
4b7649548735d6583d77b0fcc08406cb454da357    9728 2021-03-31  UnityEngine.ScreenCaptureModule.dll
0a6b0eaec42f1068c4cbd7a66e11b5c3d38c209f   19456 2021-03-31  UnityEngine.SharedInternalsModule.dll
b962c3ca1ffe9faaf4a2f62fb328e2c480b8c12c   10240 2021-03-31  UnityEngine.SpriteMaskModule.dll
b2250e791d3f40c6f6b101e853b046556905aa10   14336 2021-03-31  UnityEngine.SpriteShapeModule.dll
f1373a5679c1ee3486bc223a01703419ef27b70a    9728 2021-03-31  UnityEngine.StreamingModule.dll
df668874cfb86622e815852509b144c06e278eba   13824 2021-03-31  UnityEngine.SubstanceModule.dll
a968ec6d3f4d899eda9d17da82cbf4ffa4405521   16896 2021-03-31  UnityEngine.SubsystemsModule.dll
9187aa32516e9dcbc76f94332c1653b93d059505   80896 2021-03-31  UnityEngine.TerrainModule.dll
43544d0ea9e55d3ab36f34d7b8d7bc4d10652c83    9728 2021-03-31  UnityEngine.TerrainPhysicsModule.dll
bb1dcb402ac504679f545aa0eb750edbefb3811b  185344 2021-03-31  UnityEngine.TextCoreModule.dll
09e003b55c000a4aa482c19ba9c03e6f669ecf69   27648 2021-03-31  UnityEngine.TextRenderingModule.dll
939c7a40fba63bf117b5155b715a202b5d280a01   25088 2021-03-31  UnityEngine.TilemapModule.dll
226a01db999c6de9c41c66c2c79744baaa730c2d    8704 2021-03-31  UnityEngine.TLSModule.dll
d637a595dd53acde90acbe399634c92f5da9eff4  226304 2021-02-17  UnityEngine.UI.dll
577aa256b986905bb4ab86afc24f4c5ee114f566  726016 2021-03-31  UnityEngine.UIElementsModule.dll
187d89cd50d8b0eb84e3f874e389a8810aab48de   23552 2021-03-31  UnityEngine.UIModule.dll
d6ae7ca07e3961f9437ca50bde250ea6cdc9282c    8704 2021-03-31  UnityEngine.UmbraModule.dll
9be15a953f7f0cef47bc13544726d9c67235a4b0   77312 2021-03-31  UnityEngine.UNETModule.dll
739128c878f10e42e65bce65305715f8a95bc61c   32768 2021-03-31  UnityEngine.UnityAnalyticsModule.dll
42141df14fe1ac5b052aaf3e4b5bfab84af32d13   10752 2021-03-31  UnityEngine.UnityConnectModule.dll
a88ec6b65584f8dc4338cf1cf473100c9ac3eb43    8704 2021-03-31  UnityEngine.UnityTestProtocolModule.dll
dc21080933083b098483c17587541cd012b3f5a5   11776 2021-03-31  UnityEngine.UnityWebRequestAssetBundleModule.dll
d2be6f1365f72524996fb4437d7045defddfed00   11264 2021-03-31  UnityEngine.UnityWebRequestAudioModule.dll
91fce32c88cdd16f73a742a1baeac6a5f8b3ca39   43520 2021-03-31  UnityEngine.UnityWebRequestModule.dll
a06d338d1e52518810db33f2f15920e7ff3030f7   10752 2021-03-31  UnityEngine.UnityWebRequestTextureModule.dll
afb65edfe54bfadb700ad126252912d845d43e2e   20480 2021-03-31  UnityEngine.UnityWebRequestWWWModule.dll
06fba2651cd90df63bb8c2f64c849189c7764da2   12800 2021-03-31  UnityEngine.VehiclesModule.dll
dfb764896aafbae86851522d3bb8e6a3c3892fdd   38912 2021-03-31  UnityEngine.VFXModule.dll
424df9592e977161323ad75a7e2802797ba09b7b   29184 2021-03-31  UnityEngine.VideoModule.dll
52e189b87e8e03e04aebe9809c853694fe95a95a   34816 2021-03-31  UnityEngine.VRModule.dll
e583aa305228d2b65664e1b421a7581bb52e04c0    9728 2021-03-31  UnityEngine.WindModule.dll
46d380fba83d4860fa155c9b1e09ca59517a02b9   54272 2021-03-31  UnityEngine.XRModule.dll
```

</details>
