### ISSUE TITLE
Missing proxy.c and dllproxy.asm on master

### ISSUE THREAD

**Issue by SeleDreams** [NeighTools/UnityDoorstop#6] opened 2020-04-08 22:39 UTC
Hi, I'm just sending this issue because these two files seem to be missing in the latest version of master, I had to revert to older versions to be able to build the library

**Comment by denikson** [comment] 2020-04-09 06:25
Greetings!

Those two files are automatically generated by `genproxy.ps1` depending on the exported functions you define in `dll.def`. This allows you to change up the DLL to proxy easily.

If you build with VS19 on Windows, the PowerShell script is run automatically. In other cases you might need to run the script manually.

Because those two files are always automatically generated and depend on whether you're building x86/x64 version, they are not included by design as per [project's .gitignore](https://github.com/NeighTools/UnityDoorstop/blob/master/.gitignore#L6).

**Comment by denikson** [comment] 2020-04-12 09:42
Closing this issue as it's been answered and since I couldn't manage to reproduce the issue of the proxy files not being generated on VS build.

If you still have the problem, please create a new issue with steps I can attempt and reproduce.

**Closed by denikson** 2020-04-12 09:42 UTC
